- hosts: all
  roles:
    - { role:           ansible_docker,
        docker_version: "5:24.0.7-1~ubuntu.22.04~jammy"}
    - docker_compose
    - system
    - { role:              mosquitto,
        mosquitto_version: 2.0 }
    - { role:                  homeassistant,
        homeassistant_version: 2024.1.0 }
    - { role:                zigbee2mqtt,
        zigbee2mqtt_version: 1.35.0 }
    - { role:                 teslamate,
        teslamateapi_version: 1.16.6,
        teslamate_version:    1.28.2 }
    - { role:                      teslasolarcharger,
        teslasolarcharger_version: 2.23.1 }