- hosts: all
  roles:
    - { role:           "ansible_docker",
        docker_version: "5:24.0.4-1~ubuntu.22.04~jammy"}
    - docker_compose
    - system
    - mosquitto
    - openhab
    - homeassistant
    - zigbee2mqtt
    - evcc
    - teslamate
    - teslasolarcharger