- hosts: pi4
  roles:
    - role: ansible_docker
      docker_version: "5:29.1.3-1~ubuntu.22.04~jammy"
    - docker_compose
    - role: system
      system_required_users:
        - name: "{{ mosquitto_username }}"
          id: "{{ mosquitto_uid }}"
        - name: "{{ openhab_username }}"
          id: "{{ openhab_uid }}"
        - name: "{{ homeassistant_username }}"
          id: "{{ homeassistant_uid }}"
        - name: "{{ zigbee2mqtt_username }}"
          id: "{{ zigbee2mqtt_uid }}"
        - name: "{{ evcc_username }}"
          id: "{{ evcc_uid }}"
        - name: "{{ teslamate_username }}"
          id: "{{ teslamate_uid }}"
        - name: "{{ teslasolarcharger_username }}"
          id: "{{ teslasolarcharger_uid }}"
        - name: "{{ smokeping_username }}"
          id: "{{ smokeping_uid }}"
    - role: system_configure_trim
    - role: mosquitto
      mosquitto_version: 2.0
    - role: homeassistant
      homeassistant_version: 2025.12.4
    - role: zigbee2mqtt
      zigbee2mqtt_version: 2.7.1
    - role: teslamate
      teslamateapi_version: 1.20.2
      teslamate_version: 1.32.0
    - role: teslasolarcharger
      teslasolarcharger_version: 2.30.0
    - role: smokeping
      smokeping_version: 2.9.0-r0-ls159
    - role: tailscale

- hosts: pi0
  roles:
    - role: ansible_docker
      docker_version: "5:29.1.3-1~debian.13~trixie"
    - docker_compose
    - system_bluetooth_fix
    - role: system
      system_required_users:
        - name: "{{ teslasolarchargerbleapi_username }}"
          id: "{{ teslasolarchargerbleapi_uid }}"
    - role: teslasolarchargerbleapi
      teslasolarchargerbleapi_version: latest

- hosts: hp260g2
  roles:
    - role: tailscale

- hosts: micro10
  roles:
    - role: ansible_docker
      docker_version: "5:29.1.3-1~ubuntu.24.04~noble"
    - docker_compose
    - role: system
      system_required_users:
        - name: "{{ homeassistant_username }}"
          id: "{{ homeassistant_uid }}"
    - role: homeassistant
      homeassistant_version: 2025.12.4
    - role: tailscale
