- hosts: all
  roles:
    - { role:           ansible_docker,
        docker_version: "5:25.0.4-1~ubuntu.22.04~jammy"}
    - docker_compose
    - system
    - { role:              mosquitto,
        mosquitto_version: 2.0 }
    - { role:                  homeassistant,
        homeassistant_version: 2024.3.1 }
    - { role:                zigbee2mqtt,
        zigbee2mqtt_version: 1.36.0 }
    - { role:                 teslamate,
        teslamateapi_version: 1.16.6,
        teslamate_version:    1.28.3 }
    - { role:                      teslasolarcharger,
        teslasolarcharger_version: 2.24.7 }
    - { role:              smokeping,
        smokeping_version: 2.8.2-r3-ls77 }