- hosts: all
  roles:
    - { role:           ansible_docker,
        docker_version: "5:24.0.5-1~ubuntu.22.04~jammy"}
    - docker_compose
    - system
    - { role:              mosquitto,
        mosquitto_version: 2.0 }
    - { role:                  homeassistant,
        homeassistant_version: 2023.11.3 }
    - { role:                zigbee2mqtt,
        zigbee2mqtt_version: 1.33.0 }
    - { role:                 teslamate,
        teslamateapi_version: 1.16.5,
        teslamate_version:    1.27.4 }
    - { role:                      teslasolarcharger,
        teslasolarcharger_version: 2.22.0 }