version: '3'

services:
  openhab:
    image: "openhab/openhab:{{ openhab_version }}"
    restart: always
    network_mode: host
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "{{ openhab_home}}/addons:/openhab/addons"
      - "{{ openhab_home}}/conf:/openhab/conf"
      - "{{ openhab_home}}/userdata:/openhab/userdata"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Bucharest"