services:
  fluentd:
    depends_on:
      vlagent:
        condition: service_started
    healthcheck:
      test: ["CMD", "nc", "-z", "-n", "-v", "127.0.0.1", "24224"]
      start_period: 3s
    image: fluent/fluentd:v{{ fluentd_version }}
    network_mode: host
    restart: unless-stopped
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - "{{ victoriametrics_home }}/conf/fluent.conf:/fluentd/etc/fluent.conf"

  # Grafana instance configured with VictoriaLogs and VictoriaMetrics as datasources
  vlgrafana:
    image: grafana/grafana:12.4.5
    depends_on:
      - "victoriametrics"
      - "victorialogs"
    environment:
      - "GF_INSTALL_PLUGINS=victoriametrics-logs-datasource"
    networks:
      - home_automation
    ports:
      - 3010:3000
    restart: unless-stopped
    volumes:
      - "{{ victoriametrics_home }}/grafana-data:/var/lib/grafana"
      - "{{ victoriametrics_home }}/conf/dashboards:/var/lib/grafana/dashboards"
      - type: bind
        source: "{{ victoriametrics_home }}/conf/dashboards.yml"
        target: /etc/grafana/provisioning/dashboards/dashboards.yml
      - type: bind
        source: "{{ victoriametrics_home }}/conf/datasources.yml"
        target: /etc/grafana/provisioning/datasources/datasources.yml

  vlagent:
    command:
      - '--remoteWrite.tmpDataPath=/vlagent'
      - '--remoteWrite.url=http://victorialogs:9428/insert/native'
    depends_on:
      victorialogs:
        condition: service_started
    image: victoriametrics/vlagent:v{{ victoria_logs_version }}
    networks:
      - home_automation
    ports:
      - "9429:9429"
    restart: unless-stopped
    volumes:
      - "{{ victoriametrics_home }}/agent:/vlagent"

  #  VictoriaLogs instance, a single process responsible for
  #  storing logs and serving read queries.
  victorialogs:
    command:
      - --storageDataPath=/vlogs
      - -loggerFormat=json
      - -retentionPeriod=1y
    image: victoriametrics/victoria-logs:v{{ victoria_logs_version }}
    networks:
      - home_automation
    ports:
      - "9428:9428"
    restart: unless-stopped
    volumes:
      - "{{ victoriametrics_home }}/logs-data:/vlogs"

  # VictoriaMetrics instance, a single process responsible for
  # scraping, storing metrics and serve read requests.
  victoriametrics:
    image: victoriametrics/victoria-metrics:v{{ victoria_metrics_version }}
    command:
      - --storageDataPath=/vmsingle
      - --promscrape.config=/etc/prometheus/prometheus.yml
      - -loggerFormat=json
    networks:
      - home_automation
    volumes:
      - type: bind
        source: "{{ victoriametrics_home }}/conf/prometheus.yml"
        target: /etc/prometheus/prometheus.yml
      - "{{ victoriametrics_home }}/metrics-data:/vmsingle"

  vmauth:
    command: -auth.config=/etc/vmauth.yml
    depends_on:
      - "victoriametrics"
      - "victorialogs"
    image: docker.io/victoriametrics/vmauth:v{{ victoria_metrics_version }}
    networks:
      - home_automation
    ports:
      - '8427:8427'
    restart: unless-stopped
    volumes:
      - type: bind
        source: "{{ victoriametrics_home }}/conf/vmauth.yml"
        target: /etc/vmauth.yml

networks:
  home_automation:
    external: true
    name: home_automation