version: "3"
services:
  teslasolarcharger:
    image: pkuehnel/teslasolarcharger:{{ teslasolarcharger_version }}
    container_name: teslasolarcharger
    restart: always
    environment:
#      - Serilog__MinimumLevel__Default=Verbose #uncomment this line and recreate container with docker-compose up -d for more detailed logs
      - TZ=Europe/Bucharest ##You can change your Timezone here
    ports:
      - 7190:80
    networks:
      - home_automation
    volumes:
      - "{{ teslasolarcharger_home }}/configs:/app/configs"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  home_automation:
    external: true
    name: home_automation
