services:
  teslasolarcharger:
    container_name: teslasolarcharger
    environment:
      # uncomment this line and recreate container with docker-compose up -d for more detailed logs
      # - Serilog__MinimumLevel__Default=Verbose
      - Serilog__MinimumLevel__Default=Information
      - Serilog__MinimumLevel__Override__TeslaSolarCharger.Server.Services.TeslaFleetApiService=Fatal
      - TZ=Europe/Bucharest ##You can change your Timezone here
      # - UseFleetApi=False
      - SendTeslaApiStatsToBackend=False
      - BleBaseUrl=http://{{ hostvars['pi0']['ansible_host'] }}:7210/api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: pkuehnel/teslasolarcharger:{{ teslasolarcharger_version }}
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
        labels: com.docker.compose.service
    networks:
      - home_automation
    ports:
      - 7190:80
    restart: unless-stopped
    volumes:
      - "{{ teslasolarcharger_home }}/configs:/app/configs"

networks:
  home_automation:
    external: true
    name: home_automation
