- name: ensure the required groups exists
  group:
    name: "{{ item.name }}"
    gid: "{{ item.id }}"
    state: present
  loop:
    - name: "{{ mosquitto_username }}"
      id: "{{ mosquitto_uid }}"
    - name: "{{ openhab_username }}"
      id: "{{ openhab_uid }}"
    - name: "{{ homeassistant_username }}"
      id: "{{ homeassistant_uid }}"
    - name: "{{ zigbee2mqtt_username }}"
      id: "{{ zigbee2mqtt_uid }}"
    - name: "{{ evcc_username }}"
      id: "{{ evcc_uid }}"
    - name: "{{ teslamate_username }}"
      id: "{{ teslamate_uid }}"
    - name: "{{ teslasolarcharger_username }}"
      id: "{{ teslasolarcharger_uid }}"
  become: yes
  tags:
    - system

- name: ensure the required users exists
  user:
    name: "{{ item.name }}"
    shell: /sbin/nologin
    uid: "{{ item.id }}"
    groups: "{{ item.name }},docker"
    append: yes
  loop:
    - name: "{{ mosquitto_username }}"
      id: "{{ mosquitto_uid }}"
    - name: "{{ openhab_username }}"
      id: "{{ openhab_uid }}"
    - name: "{{ homeassistant_username }}"
      id: "{{ homeassistant_uid }}"
    - name: "{{ zigbee2mqtt_username }}"
      id: "{{ zigbee2mqtt_uid }}"
    - name: "{{ evcc_username }}"
      id: "{{ evcc_uid }}"
    - name: "{{ teslamate_username }}"
      id: "{{ teslamate_uid }}"
    - name: "{{ teslasolarcharger_username }}"
      id: "{{ teslasolarcharger_uid }}"
  become: yes
  tags:
    - system

- name: ensure the required system dependencies exist
  package:
    name:
      - python3-pip
  become: yes
  tags:
    - system

- name: ensure the required python dependencies exist
  pip:
    name:
      - docker
  become: yes
  tags:
    - system

- name: ensure the home_automation docker network exists
  docker_network:
    name: home_automation
  become: yes
  tags:
    - system

- include_tasks: configure-trim.yml
  when: configure_trim
  tags:
    - system
    - trim
