- name: ensure the openhab group exists
  group:
    name: "{{ openhab_username }}"
    gid: "{{ openhab_uid }}"
    state: present
  become: yes
  tags:
    - system

- name: ensure the openhab user exists
  user:
    name: "{{ openhab_username }}"
    shell: /sbin/nologin
    uid: "{{ openhab_uid }}"
    groups: "{{ openhab_username }},docker"
    append: yes
  become: yes
  tags:
    - system

- include_tasks: configure-trim.yml
  when: configure_trim
  tags:
    - system
    - trim