- name: ensure the required groups exists
  group:
    name: "{{ item.name }}"
    gid: "{{ item.id }}"
    state: present
  loop:
    - name: "{{ mosquitto_username }}"
      id: "{{ mosquitto_uid }}"
    - name: "{{ openhab_username }}"
      id: "{{ openhab_uid }}"
  become: yes
  tags:
    - system

- name: ensure the required users exists
  user:
    name: "{{ item.name }}"
    shell: /sbin/nologin
    uid: "{{ item.id }}"
    groups: "{{ item.name }},docker"
    append: yes
  loop:
    - name: "{{ mosquitto_username }}"
      id: "{{ mosquitto_uid }}"
    - name: "{{ openhab_username }}"
      id: "{{ openhab_uid }}"
  become: yes
  tags:
    - system

- include_tasks: configure-trim.yml
  when: configure_trim
  tags:
    - system
    - trim