- name: ensure the required groups exists
  ansible.builtin.group:
    name: "{{ item.name }}"
    gid: "{{ item.id }}"
    state: present
  loop: "{{ system_required_users }}"
  become: yes
  tags:
    - system

- name: ensure the required users exists
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: /sbin/nologin
    uid: "{{ item.id }}"
    groups: "{{ item.name }},docker"
    append: yes
  loop: "{{ system_required_users }}"
  become: yes
  tags:
    - system

- name: ensure the required system dependencies exist
  ansible.builtin.package:
    name:
      - python3-pip
      - python3-docker
  become: yes
  tags:
    - system

- name: ensure the home_automation docker network exists
  community.docker.docker_network:
    name: home_automation
  become: yes
  tags:
    - system

- ansible.builtin.include_tasks: configure-trim.yml
  when: system_configure_trim
  tags:
    - system
    - trim
