- name: ensure the tailscale repo key is available
  ansible.builtin.get_url:
    url: "https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}.noarmor.gpg"
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
    mode: 0644
    owner: root
    group: root
  become: true
  tags: tailscale

- name: ensure that the tailscale repo is available
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }} {{ ansible_lsb.codename }} main"
    state: present
    update_cache: false
  become: true
  tags: tailscale

- name: ensure tailscale is installed
  ansible.builtin.apt:
    name:
      - tailscale
      - tailscale-archive-keyring
    update_cache: true
    state: present
  become: true
  tags: tailscale

- name: ensure tailscale service is enabled to start at boot
  ansible.builtin.systemd:
    name: tailscaled
    enabled: true
    daemon_reload: true
  become: true
  tags: tailscale
