services:
  mosquitto:
    container_name: mosquitto
    image: "eclipse-mosquitto:{{ mosquitto_version }}"
    restart: unless-stopped
    volumes:
      - "{{ mosquitto_home}}/config:/mosquitto/config"
      - "{{ mosquitto_home}}/data:/mosquitto/data"
      - "{{ mosquitto_home}}/etc:/etc/mosquitto"
      - "{{ mosquitto_home}}/log:/mosquitto/log"
    user: "{{ mosquitto_uid }}:{{ mosquitto_uid }}"
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - home_automation

networks:
  home_automation:
    external: true
    name: home_automation