services:
  broker:
    image: "eclipse-mosquitto:{{ mosquitto_version }}"
    restart: always
    volumes:
      - "{{ mosquitto_home}}/config:/mosquitto/config"
      - "{{ mosquitto_home}}/data:/mosquitto/data"
      - "{{ mosquitto_home}}/etc:/etc/mosquitto"
      - "{{ mosquitto_home}}/log:/mosquitto/log"
    user: "{{ mosquitto_uid }}:{{ mosquitto_uid }}"
    ports:
      - 1883:1883
      - 9001:9001
