- name: ensure necessary local dirs on remote machines exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ evcc_username }}"
    group: "{{ evcc_username }}"
    mode: 0755
  become: yes
  with_items:
    - "{{ evcc_home }}"
    - "{{ evcc_home }}/.evcc"
  tags:
    - evcc

- name: ensure the configuration is up-to-date
  template:
    src: evcc.yaml.j2
    dest: "{{ evcc_home }}/evcc.yaml"
    owner: "{{ evcc_username }}"
    group: "{{ evcc_username }}"
    mode: 0644
  become: yes
  notify:
    - restart evcc
  tags:
    - evcc

- name: ensure the stack definition is up-to-date
  template:
    src: docker-compose.j2.yml
    dest: "{{ evcc_home }}/docker-compose.yml"
    owner: "{{ evcc_username }}"
    group: "{{ evcc_username }}"
    mode: 0644
  become: yes
  tags:
    - evcc

- name: ensure evcc service is enabled to start at boot
  systemd:
    name: "docker-compose@evcc"
    enabled: true
    daemon_reload: true
  become: true
  tags:
    - evcc
