services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: "koenkk/zigbee2mqtt:{{ zigbee2mqtt_version }}"
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
        labels: com.docker.compose.service
    networks:
      - home_automation
    ports:
      - 9080:9080
    restart: unless-stopped
    user: "{{ zigbee2mqtt_uid }}:{{ zigbee2mqtt_uid }}"
    volumes:
      - "{{ zigbee2mqtt_home }}/data:/app/data"
      - /etc/localtime:/etc/localtime:ro

networks:
  home_automation:
    external: true
    name: home_automation

