services:
  teslamate:
    cap_drop:
      - all
    container_name: teslamate
    depends_on:
      - database
    environment:
      - ENCRYPTION_KEY={{ teslamate_encryption_key }}
      - DATABASE_USER={{ teslamate_username }}
      - DATABASE_PASS={{ teslamate_database_password }}
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=192.168.1.10
      - MQTT_USERNAME={{ mosquitto_user }}
      - MQTT_PASSWORD={{ mosquitto_pass_clear }}
      - TZ=Europe/Bucharest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: teslamate/teslamate:{{ teslamate_version }}
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
        labels: com.docker.compose.service
    networks:
      - home_automation
    ports:
      - 4000:4000
    restart: unless-stopped
    volumes:
      - "{{ teslamate_home }}/import:/opt/app/import"

  teslamateapi:
    container_name: teslamateapi
    depends_on:
      - database
    environment:
      - ENCRYPTION_KEY={{ teslamate_encryption_key }}
      - DATABASE_USER={{ teslamate_username }}
      - DATABASE_PASS={{ teslamate_database_password }}
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=192.168.1.10
      - MQTT_USERNAME={{ mosquitto_user }}
      - MQTT_PASSWORD={{ mosquitto_pass_clear }}
      - ENABLE_COMMANDS=true
      - COMMANDS_ALL=true
      - API_TOKEN_DISABLE=true
      - TZ=Europe/Bucharest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: tobiasehlert/teslamateapi:{{ teslamateapi_version }}
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
        labels: com.docker.compose.service
    networks:
      - home_automation
    ports:
      - 8080:8080
    restart: unless-stopped

  database:
    container_name: database
    environment:
      - POSTGRES_USER={{ teslamate_username }}
      - POSTGRES_PASSWORD={{ teslamate_database_password }}
      - POSTGRES_DB=teslamate
    image: postgres:18-trixie
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
        labels: com.docker.compose.service
    networks:
      - home_automation
    restart: unless-stopped
    volumes:
      - "{{ teslamate_home }}/db-data:/var/lib/postgresql"

  grafana:
    container_name: grafana
    environment:
      - DATABASE_USER={{ teslamate_username }}
      - DATABASE_PASS={{ teslamate_database_password }}
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    image: teslamate/grafana:{{ teslamate_version }}
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
        labels: com.docker.compose.service
    networks:
      - home_automation
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - "{{ teslamate_home }}/grafana-data:/var/lib/grafana"

networks:
  home_automation:
    external: true
    name: home_automation