- name: ensure necessary local dirs on remote machines exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ mosquitto_username }}"
    group: "{{ mosquitto_username }}"
    mode: 0774
  become: yes
  with_items:
    - "{{ mosquitto_home }}"
    - "{{ mosquitto_home }}/config"
    - "{{ mosquitto_home }}/data"
    - "{{ mosquitto_home }}/etc"
    - "{{ mosquitto_home }}/log"
  tags:
    - mosquitto

- name: ensure the config is up-to-date
  ansible.builtin.template:
    src: mosquitto.conf.j2
    dest: "{{ mosquitto_home }}/config/mosquitto.conf"
    owner: "{{ mosquitto_username }}"
    group: "{{ mosquitto_username }}"
    mode: 0664
  become: yes
  notify:
    - restart mosquitto
  tags:
    - mosquitto

- name: ensure the auth config is up-to-date
  ansible.builtin.template:
    src: passwd.j2
    dest: "{{ mosquitto_home }}/etc/passwd"
    owner: "{{ mosquitto_username }}"
    group: "{{ mosquitto_username }}"
    mode: 0644
  become: yes
  notify:
    - restart mosquitto
  tags:
    - mosquitto

- name: ensure the stack definition is up-to-date
  ansible.builtin.template:
    src: docker-compose.j2.yml
    dest: "{{ mosquitto_home }}/docker-compose.yml"
    owner: "{{ mosquitto_username }}"
    group: "{{ mosquitto_username }}"
    mode: 0664
  become: yes
  notify:
    - restart mosquitto
  tags:
    - mosquitto

- name: ensure mosquitto service is enabled to start at boot
  ansible.builtin.systemd:
    name: "docker-compose@mosquitto"
    enabled: yes
    daemon_reload: yes
  become: yes
  tags:
    - mosquitto
