---
- name: ensure that the generic docker-compose unit file is configured
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  become: true
  with_items:
    - src: docker-compose-w1@.service.j2
      dest: /etc/systemd/system/docker-compose-w1@.service
    - src: docker-compose-w2@.service.j2
      dest: /etc/systemd/system/docker-compose-w2@.service
  tags: docker_compose